[workspace]
resolver = "2"
members = ["./layershellev", "./starcolorkeyboard", "./sessionlockev"]

[workspace.package]
authors = [
	"Decodertalkers <aakari@tutanota.com>",
	"Aakash Sen Sharma <aakashsensharma@gmail.com>",
]
edition = "2021"
version = "0.1.0"
license = "MIT"
repository = "https://github.com/waycrate/exwlshelleventloop"
description = "Wayland extra shell lib"
keywords = ["wayland", "wlroots"]
readme = "README.md"

[workspace.dependencies]
layershellev = { version = "0.1.0", path = "./layershellev" }
sessionlockev = { version = "0.1.0", path = "./sessionlockev" }

tempfile = "3.8.1"
thiserror = "1.0.50"
wayland-client = { version = "0.31.1" }

wayland-protocols = { version = "0.31.0", default-features = false, features = [
	"unstable",
	"staging",
	"client",
] }

wayland-cursor = "0.31.0"

wayland-protocols-wlr = { version = "0.2.0", default-features = false, features = [
	"client",
] }

wayland-protocols-misc = { version = "0.2.0", features = ["client"] }
wayland-backend = { version = "0.3.0", features = ["client_system"] }

rwh_05 = { package = "raw-window-handle", version = "0.5.2", features = ["std"] }
rwh_06 = { package = "raw-window-handle", version = "0.6", features = ["std"]}
