[workspace]
resolver = "2"
members = [
	"layershellev",
	"iced_layershell",
	"iced_sessionlock",
	"starcolorkeyboard",
	"sessionlockev",
	"waycrate_xkbkeycode",
	"iced_examples/*",
]

[workspace.package]
authors = [
	"Decodertalkers <aakari@tutanota.com>",
	"Aakash Sen Sharma <aakashsensharma@gmail.com>",
]
edition = "2021"
version = "0.6.0-dev"
license = "MIT"
repository = "https://github.com/waycrate/exwlshelleventloop"
description = "Wayland extra shell lib"
keywords = ["wayland", "wlroots"]
readme = "README.md"

[workspace.dependencies]
layershellev = { version = "0.6.0-dev", path = "./layershellev" }
sessionlockev = { version = "0.6.0-dev", path = "./sessionlockev" }

iced_layershell = { version = "0.6.0-dev", path = "./iced_layershell" }
iced_sessionlock = { version = "0.6.0-dev", path = "./iced_sessionlock" }
waycrate_xkbkeycode = { version = "0.6.0-dev", path = "./waycrate_xkbkeycode" }

tempfile = "3.12.0"
thiserror = "1.0.63"
wayland-client = { version = "0.31.5" }

wayland-protocols = { version = "0.32.3", default-features = false, features = [
	"unstable",
	"staging",
	"client",
] }

wayland-cursor = "0.31.5"

wayland-protocols-wlr = { version = "0.3.3", default-features = false, features = [
	"client",
] }

wayland-protocols-misc = { version = "0.3.3", features = ["client"] }
wayland-backend = { version = "0.3.6", features = ["client_system"] }

sctk = { package = "smithay-client-toolkit", version = "0.18.1", features = [
	"calloop",
] }

calloop = "0.14.0"

rwh_05 = { package = "raw-window-handle", version = "0.5.2", features = [
	"std",
] }
rwh_06 = { package = "raw-window-handle", version = "0.6", features = ["std"] }

iced = "0.12"
iced_runtime = { version = "0.12", features = ["multi-window"] }
iced_style = "0.12"
iced_core = "0.12"
iced_renderer = "0.12.1"
iced_futures = "0.12.0"
iced_graphics = "0.12.1"
bitflags = "2.6.0"
log = "0.4.22"

xkbcommon-dl = "0.4.2"
smol_str = "0.2.2"
memmap2 = "0.9.4"

tracing = "0.1.40"
futures = "0.3.30"
