[workspace]
resolver = "2"
members = [
	"layershellev",
	"iced_layershell",
	"iced_sessionlock",
	"starcolorkeyboard",
	"sessionlockev",
	"iced_examples/*",
]

[workspace.package]
authors = [
	"Decodertalkers <aakari@tutanota.com>",
	"Aakash Sen Sharma <aakashsensharma@gmail.com>",
]
edition = "2021"
version = "0.2.3"
license = "MIT"
repository = "https://github.com/waycrate/exwlshelleventloop"
description = "Wayland extra shell lib"
keywords = ["wayland", "wlroots"]
readme = "README.md"

[workspace.dependencies]
layershellev = { version = "0.2.3", path = "./layershellev" }
sessionlockev = { version = "0.2.3", path = "./sessionlockev" }

iced_layershell = { version = "0.2.3", path = "./iced_layershell" }
iced_sessionlock = { version = "0.2.3", path = "./iced_sessionlock"}

tempfile = "3.8.1"
thiserror = "1.0.50"
wayland-client = { version = "0.31.1" }

wayland-protocols = { version = "0.31.0", default-features = false, features = [
	"unstable",
	"staging",
	"client",
] }

wayland-cursor = "0.31.0"

wayland-protocols-wlr = { version = "0.2.0", default-features = false, features = [
	"client",
] }

wayland-protocols-misc = { version = "0.2.0", features = ["client"] }
wayland-backend = { version = "0.3.0", features = ["client_system"] }

sctk = { package = "smithay-client-toolkit", version = "0.18.1", features = [
	"calloop",
] }

calloop = "0.12.3"

rwh_05 = { package = "raw-window-handle", version = "0.5.2", features = [
	"std",
] }
rwh_06 = { package = "raw-window-handle", version = "0.6", features = ["std"] }

iced = "0.12"
iced_runtime = { version = "0.12", features = ["multi-window"] }
iced_style = "0.12"
iced_core = "0.12"
iced_renderer = "0.12.0"
iced_futures = "0.12.0"
iced_graphics = "0.12.0"
bitflags = "2.4.0"
