[workspace]
resolver = "2"
members = [
  "layershellev",
  "iced_layershell",
  "iced_layershell_macros",
  "iced_sessionlock",
  "iced_sessionlock_macros",
  "starcolorkeyboard",
  "sessionlockev",
  "waycrate_xkbkeycode",
  "iced_examples/*",
]

[workspace.package]
authors = [
  "Decodertalkers <aakari@tutanota.com>",
  "Aakash Sen Sharma <aakashsensharma@gmail.com>",
]
edition = "2021"
version = "0.8.0"
license = "MIT"
repository = "https://github.com/waycrate/exwlshelleventloop"
description = "Wayland extra shell lib"
keywords = ["wayland", "wlroots"]
readme = "README.md"

[workspace.dependencies]
layershellev = { version = "0.8.0", path = "./layershellev" }
sessionlockev = { version = "0.8.0", path = "./sessionlockev" }

iced_layershell = { version = "0.8.0", path = "./iced_layershell" }
iced_layershell_macros = { version = "0.8.0", path = "./iced_layershell_macros" }
iced_sessionlock = { version = "0.8.0", path = "./iced_sessionlock" }
waycrate_xkbkeycode = { version = "0.8.0", path = "./waycrate_xkbkeycode" }

tempfile = "3.12.0"
thiserror = "1.0.63"
wayland-client = { version = "0.31.5" }

wayland-protocols = { version = "0.32.3", default-features = false, features = [
  "unstable",
  "staging",
  "client",
] }

wayland-cursor = "0.31.5"

wayland-protocols-wlr = { version = "0.3.3", default-features = false, features = [
  "client",
] }

wayland-protocols-misc = { version = "0.3.3", features = ["client"] }
wayland-backend = { version = "0.3.6", features = ["client_system"] }

sctk = { package = "smithay-client-toolkit", version = "0.18.1", features = [
  "calloop",
] }

calloop = "0.14.0"

rwh_05 = { package = "raw-window-handle", version = "0.5.2", features = [
  "std",
] }
rwh_06 = { package = "raw-window-handle", version = "0.6", features = ["std"] }

iced = "0.13"
iced_runtime = { version = "0.13", features = ["multi-window"] }
#iced_style = "0.13"
iced_core = "0.13"
iced_renderer = "0.13"
iced_futures = "0.13"
iced_graphics = "0.13"
window_clipboard = "0.4.1"

bitflags = "2.6.0"
log = "0.4.22"

xkbcommon-dl = "0.4.2"
smol_str = "0.2.2"
memmap2 = "0.9.4"

tracing = "0.1.40"
futures = "0.3.30"

darling = { version = "0.20.10", features = ["suggestions"] }
manyhow = { version = "0.11.4", features = ["darling"] }
proc-macro2 = "1.0.86"
quote = "1.0.37"
syn = { version = "2.0.77", features = ["full"] }
