[package]
name = "iced_layershell"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sctk.workspace = true
iced_runtime = "0.12"
iced_style = "0.12"
iced_core = "0.12"
iced_futures = "0.12.0"
iced_graphics = "0.12.0"
tracing = "0.1.40"
thiserror = "1.0.56"
layershellev.workspace = true
futures = "0.3.30"
rwh_06.workspace = true
